stages:
  - build
  - test
  - package
  - deploy

image: node:16.14.2-alpine3.15

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

build:
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run nx-run-many -- --target=build --configuration=production --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - dist/apps

code style:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run format:check
    - npm run nx-run-many -- --target=lint --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

unit test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run nx-run-many -- --target=test --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

package api:
  stage: package
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/api:latest -f ./apps/api/Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

package fe-web:
  stage: package
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/fe-web:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/fe-web:latest -f ./apps/fe-web/Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

deploy:
  stage: deploy
  cache: {}
  script:
    - echo "deploy"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
