stages:
  - build
  - test
  - package

image: node:18.10.0-alpine3.15

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

build:
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run nx-run-many -- --target=build --configuration=production --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - dist/apps

code style:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run format:check
    - npm run nx-run-many -- --target=lint --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

unit test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm run prisma
  script:
    - npm run nx-run-many -- --target=test --all
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

package api:
  stage: package
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/list-app-api:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/list-app-api:latest -f ./apps/api/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/list-app-api:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/list-app-api:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

package web:
  stage: package
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  cache: {}
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/list-app-web:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/list-app-web:latest -f ./apps/web/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/list-app-web:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/list-app-web:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
